import { Card, EmptyState, PageHeader, StatusPill } from "@/components/ui";
import { Icon } from "@/components/icons";
import { loadProductData } from "@/lib/product/data";
import { mapAuditTimeline } from "@/lib/product/audit";
import { formatNumber, shortAddress } from "@/lib/product/format";
export const dynamic = "force-dynamic";
export default async function ActivityPage() { const data = await loadProductData(); const events = mapAuditTimeline(data.auditEvents, data.executions); return <div className="page"><PageHeader eyebrow="IMMUTABLE ACCOUNTABILITY" title="Activity & Audit Trail" description="Chronological evidence for observations, decisions, safety gates, and executions."><StatusPill tone="blue">{events.length} EVENTS</StatusPill></PageHeader>
  {events.length ? <Card className="audit-card"><div className="audit-list">{events.map(event => <article className="audit-event" key={event.id}><div className={`audit-dot ${event.tone}`}>{event.tone === "good" ? <Icon name="check"/> : event.tone === "warn" || event.tone === "danger" ? "!" : <span/>}</div><time>{new Date(event.timestamp).toLocaleDateString(undefined, { month: "short", day: "numeric" })}<small>{new Date(event.timestamp).toLocaleTimeString(undefined, { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</small></time><div className="audit-content"><div><h3>{event.title}</h3><StatusPill tone={event.tone}>{event.type}</StatusPill></div><p>{event.detail}</p>{event.execution && <div className="execution-proof"><span>Action <b>{event.execution.action.replaceAll("_", " ")}</b></span><span>Amount <b>{event.execution.displayAmount} {event.execution.asset}</b></span><span>Health factor <b>{formatNumber(event.execution.healthFactorBefore, 6)} → {formatNumber(event.execution.healthFactorAfter, 6)}</b></span><span>Receipt <b>{event.execution.receiptVerified ? "Verified" : "Not verified"}</b></span>{event.execution.keeperHubExecutionId && <span>KeeperHub ID <code>{event.execution.keeperHubExecutionId}</code></span>}{event.execution.transactionHash && <span>Transaction <code>{shortAddress(event.execution.transactionHash, 10, 8)}</code></span>}{event.execution.transactionLink && <a href={event.execution.transactionLink} target="_blank" rel="noreferrer">View on BaseScan <Icon name="external"/></a>}</div>}</div></article>)}</div></Card> : <Card><EmptyState title="No audit events yet">Monitoring and execution events will appear here from the database. PositionGuard does not create cosmetic activity.</EmptyState></Card>}
  <div className="audit-note"><Icon name="database"/><p><b>Database-backed evidence.</b> This page combines persisted audit records and execution receipts. Transaction details are never hardcoded into the interface.</p></div></div>; }
