"use client";
import { useState } from "react";
import { StatusPill } from "./ui";
type Readiness = { state: string; requiredAsset: string; requiredAmount: string; availableBalance: string | null; currentAllowance: string | null; requiredAllowance: string; sender: string | null };
export function FundingPanel({ chainId, spender }: { chainId: number; spender: string }) {
  const [data, setData] = useState<{ readiness: Readiness | null; ux: { status: string; explanation: string; action: string | null } } | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function check() { setBusy(true); setError(""); try { const response = await fetch(`/api/funding-readiness?chainId=${chainId}`); const body = await response.json() as typeof data & { error?: { code?: string } }; if (!response.ok || !body) throw new Error(body?.error?.code ?? "Readiness check failed"); setData(body); } catch (caught) { setError(caught instanceof Error ? caught.message : "Readiness check failed"); } finally { setBusy(false); } }
  const readiness = data?.readiness; return <section className="card funding-panel"><div className="section-heading"><div><span className="label">Protection Funding</span><h2>Make protection ready</h2><p className="section-description">PositionGuard never moves funds or requests unlimited approval silently.</p></div>{data && <StatusPill tone={data.ux.status === "READY" ? "good" : "warn"}>{data.ux.status}</StatusPill>}</div>{data ? <><p className="funding-explanation">{data.ux.explanation}</p><dl><div><dt>Required protection asset</dt><dd>{readiness?.requiredAsset ?? "Not selected"}</dd></div><div><dt>Required amount</dt><dd>{readiness?.requiredAmount ?? "—"}</dd></div><div><dt>Available protection balance</dt><dd>{readiness?.availableBalance ?? "Unavailable"}</dd></div><div><dt>Current Aave allowance</dt><dd>{readiness?.currentAllowance ?? "Unavailable"}</dd></div><div><dt>Required allowance</dt><dd>{readiness?.requiredAllowance ?? "—"}</dd></div><div><dt>Funding destination</dt><dd><code>{readiness?.sender ?? "Unavailable"}</code></dd></div><div><dt>Approval spender</dt><dd><code>{spender}</code></dd></div></dl>{data.ux.action && <div className="funding-guidance"><b>What to do next</b><p>{data.ux.action}</p>{readiness?.state === "INSUFFICIENT_ALLOWANCE" && <p>Token: {readiness.requiredAsset}. Spender: Aave Pool. Purpose: allow only the selected protection amount. Maximum requested: {readiness.requiredAllowance}. Do not use unlimited approval.</p>}</div>}</> : <p className="empty-row">Check the exact asset, balance, allowance, funding destination, and protection-service readiness for the current action.</p>}<button type="button" className="button secondary" disabled={busy} onClick={() => void check()}>{busy ? "Checking…" : "Check funding readiness"}</button>{error && <p className="form-status error" role="alert">{error}</p>}</section>;
}
