"use client";
import { useState } from "react";
import type { ProductPolicy } from "@/lib/product/models";
import { Icon } from "./icons";
const fields = [["targetHealthFactor", "Target health factor", "PositionGuard aims to restore the position to this level."], ["warningHealthFactor", "Warning health factor", "Risk monitoring escalates below this level."], ["emergencyHealthFactor", "Emergency health factor", "Critical status begins below this level."], ["maxAutonomousAmountUsd", "Maximum autonomous intervention", "Maximum capital allowed in a single autonomous action."], ["maxDailyAutonomousAmountUsd", "Maximum daily autonomous spend", "Aggregate autonomous capital permitted in 24 hours."], ["approvalRequiredAboveUsd", "Approval required above", "Actions over this amount cannot execute autonomously."]] as const;
export function PolicyForm({ initial }: { initial: ProductPolicy }) {
  const [policy, setPolicy] = useState(initial); const [token, setToken] = useState(""); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  function set(key: keyof ProductPolicy, value: string | boolean | number) { setPolicy(current => ({ ...current, [key]: value })); }
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setStatus(""); try { const payload = { targetHealthFactor: policy.targetHealthFactor, warningHealthFactor: policy.warningHealthFactor, emergencyHealthFactor: policy.emergencyHealthFactor, maxAutonomousAmountUsd: policy.maxAutonomousAmountUsd, maxDailyAutonomousAmountUsd: policy.maxDailyAutonomousAmountUsd, approvalRequiredAboveUsd: policy.approvalRequiredAboveUsd, allowRepay: policy.allowRepay, allowAddCollateral: policy.allowAddCollateral, interventionCooldownMinutes: policy.interventionCooldownMinutes, enabled: policy.enabled }; const response = await fetch("/api/policy", { method: "PUT", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify(payload) }); const body = await response.json() as { ok?: boolean; error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? "Policy update failed"); setStatus("Protection policy saved and server-validated."); } catch (error) { setStatus(error instanceof Error ? error.message : "Policy update failed"); } finally { setBusy(false); } }
  return <form className="policy-form" onSubmit={save}><section className="card"><div className="section-heading"><div><span className="label">Risk thresholds</span><h2>Health factor policy</h2></div><span className="ordering">Target &gt; Warning &gt; Emergency &gt; 1.00</span></div><div className="form-grid">{fields.slice(0,3).map(([key,label,help]) => <label key={key}><span>{label}</span><input inputMode="decimal" value={String(policy[key])} onChange={event => set(key, event.target.value)} required/><small>{help}</small></label>)}</div></section>
    <section className="card"><div className="section-heading"><div><span className="label">Capital limits</span><h2>Autonomous guardrails</h2></div></div><div className="form-grid">{fields.slice(3).map(([key,label,help]) => <label key={key}><span>{label}</span><div className="money-input"><i>$</i><input inputMode="decimal" value={String(policy[key])} onChange={event => set(key, event.target.value)} required/></div><small>{help}</small></label>)}</div><label className="wide-field"><span>Intervention cooldown</span><div className="suffix-input"><input type="number" min="0" max="525600" value={policy.interventionCooldownMinutes} onChange={event => set("interventionCooldownMinutes", Number(event.target.value))}/><i>minutes</i></div><small>Minimum delay between autonomous executions.</small></label></section>
    <section className="card"><div className="section-heading"><div><span className="label">Permissions</span><h2>Allowed protection actions</h2></div></div><Toggle checked={policy.allowRepay} setChecked={value => set("allowRepay", value)} title="Repay debt" copy="Allow PositionGuard to repay a supported Aave debt asset."/><Toggle checked={policy.allowAddCollateral} setChecked={value => set("allowAddCollateral", value)} title="Add collateral" copy="Allow supported wallet balances to be supplied as collateral."/><Toggle checked={policy.enabled} setChecked={value => set("enabled", value)} title="Protection enabled" copy="Monitor the position and create defensive decisions when risk thresholds are crossed." highlight/></section>
    <section className="immutable-note"><Icon name="shield"/><div><h3>Hard execution constraints</h3><p>The explanation agent and browser cannot modify these limits during execution. The server reloads and validates the active policy before constructing any canonical intent.</p></div></section>
    <section className="card authorization"><label><span>Operator authorization</span><input type="password" autoComplete="off" value={token} onChange={event => setToken(event.target.value)} placeholder="Development operator token" required/><small>Held in this page only and sent directly to the server. It is never persisted.</small></label><button className="button primary" disabled={busy}>{busy ? "Validating…" : "Save protection policy"}</button>{status && <p className="form-status" role="status">{status}</p>}</section>
  </form>;
}
function Toggle({ checked, setChecked, title, copy, highlight = false }: { checked: boolean; setChecked(value: boolean): void; title: string; copy: string; highlight?: boolean }) { return <label className={`toggle-row ${highlight ? "highlight" : ""}`}><div><b>{title}</b><small>{copy}</small></div><input type="checkbox" checked={checked} onChange={event => setChecked(event.target.checked)}/><span className="toggle"/></label>; }
