"use client";
import { useState } from "react";
import { formatNumber } from "@/lib/product/format";
type Result = { simulationOnly: true; currentHealthFactor: string | null; projectedHealthFactor: string | null; projectedRisk: string; mei: { action: string; asset: string; amount: string } | null; requiredCapitalUsd: string | null };
export function StressForm({ protectedAccountId, chainId, assets }: { protectedAccountId: string | null; chainId: number; assets: string[] }) {
  const [asset, setAsset] = useState(assets[0] ?? "WETH"); const [shock, setShock] = useState(-10); const [token, setToken] = useState(""); const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function run(event: React.FormEvent) { event.preventDefault(); if (!protectedAccountId) return; setBusy(true); setError(""); try { const response = await fetch("/api/stress", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ protectedAccountId, chainId, asset, percentageShock: shock }) }); const body = await response.json() as Result & { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? "Stress analysis failed"); setResult(body); } catch (cause) { setError(cause instanceof Error ? cause.message : "Stress analysis failed"); } finally { setBusy(false); } }
  return <><form className="card stress-form" onSubmit={run}><div className="simulation-banner"><b>SIMULATION ONLY</b><span>NO ONCHAIN STATE CHANGED</span></div><div className="form-grid"><label><span>Collateral asset</span><select value={asset} onChange={event => setAsset(event.target.value)}>{assets.map(item => <option key={item}>{item}</option>)}</select></label><label><span>Price shock</span><select value={shock} onChange={event => setShock(Number(event.target.value))}><option value={-5}>-5%</option><option value={-10}>-10%</option><option value={-20}>-20%</option></select></label><label><span>Custom percentage</span><input type="number" min="-99" max="1000" step="0.01" value={shock} onChange={event => setShock(Number(event.target.value))}/></label></div><label className="scenario-token"><span>Operator authorization</span><input type="password" value={token} onChange={event => setToken(event.target.value)} required/></label><button className="button primary" disabled={busy || !protectedAccountId}>{busy ? "Analyzing…" : "Run stress analysis"}</button>{error && <p className="form-status error">{error}</p>}</form>{result && <section className="metric-grid scenario-results"><div className="metric"><span>Current HF</span><strong>{formatNumber(result.currentHealthFactor, 2)}</strong></div><div className="metric"><span>Projected HF</span><strong>{formatNumber(result.projectedHealthFactor, 2)}</strong></div><div className="metric"><span>Projected risk</span><strong>{result.projectedRisk}</strong></div><div className="metric"><span>MEI</span><strong>{result.mei ? `${result.mei.amount} ${result.mei.asset}` : "None"}</strong><small>{result.requiredCapitalUsd ? `$${result.requiredCapitalUsd} required` : "No capital required"}</small></div></section>}</>;
}
