import { describe, expect, it } from "vitest";
import { maxUint256 } from "viem";
import { healthFactorFromWad, baseUsd, tokenValueBase } from "../../src/lib/aave/calculations";
import { normalizeAavePosition } from "../../src/lib/aave/normalizer";
import { evaluateProtection } from "../../src/lib/protection/protection-engine";
import { portfolioOutcome } from "../../src/lib/protection/portfolio-estimator";
import { previewPolicy } from "../../src/lib/aave/analysis";
import { walletSchema, positionQuerySchema } from "../../src/lib/security/position-input";
import { accountFor, baseUnit, reserves, wallet } from "../fixtures/aave";
const normalize = () => normalizeAavePosition(accountFor(reserves), reserves, baseUnit, 0n);
const context = { dailyAutonomousSpendUsd: "0", nowMs: 10000, lastAutonomousExecutionAtMs: null };
describe("Aave financial boundary", () => {
  it("preserves all 18 HF decimals", () => expect(healthFactorFromWad(1299999999999999999n, 1n)).toBe("1.299999999999999999"));
  it("uses null for maximum HF with zero debt", () => expect(healthFactorFromWad(maxUint256, 0n)).toBeNull());
  it("rejects inconsistent maximum HF", () => expect(() => healthFactorFromWad(maxUint256, 1n)).toThrow());
  it("represents zero collateral HF", () => expect(healthFactorFromWad(0n, 100n)).toBe("0"));
  it("normalizes 8 decimal account base", () => expect(baseUsd(123456789n, baseUnit)).toBe("1.23456789"));
  it("rejects unexpected base units", () => expect(() => baseUsd(1n, 10n ** 18n)).toThrow());
  it("normalizes ERC20 balances with token decimals", () => expect(tokenValueBase(1500000n, 200000000n, 6)).toBe(300000000n));
  it("does not lose large bigint precision", () => expect(baseUsd(900719925474099312345678n, baseUnit)).toBe("9007199254740993.12345678"));
  it("rejects zero prices", () => expect(() => tokenValueBase(1n, 0n, 6)).toThrow());
  it("rejects invalid addresses", () => expect(walletSchema.safeParse("0xabc").success).toBe(false));
  it("rejects unsupported chains", () => expect(positionQuerySchema.safeParse({ address: wallet, chainId: "1" }).success).toBe(false));
});
describe("multi-asset engine boundary", () => {
  it("retains multiple collateral and debt reserves", () => { const p = normalize(); expect(p.assets.filter(a => a.canSupply)).toHaveLength(2); expect(p.assets.filter(a => BigInt(a.debtBalance) > 0n)).toHaveLength(2); });
  it("preserves weighted numerator instead of rounded average threshold", () => { const p = normalize(); expect(p.weightedCollateralNumerator).toBe((1100n * baseUnit * 10000n).toString()); expect(accountFor(reserves).currentLiquidationThreshold).toBe(7333n); });
  it("repays one debt contribution without changing the other", () => { const p = normalize(); expect(portfolioOutcome(p, p.assets[2]!, "REPAY_DEBT", 200_000_000n)).toBe(1375000000000000000n); });
  it("uses the added asset threshold", () => { const p = normalize(); expect(portfolioOutcome(p, p.assets[0]!, "ADD_COLLATERAL", 100_000_000n)).toBe(1180000000000000000n); expect(portfolioOutcome(p, p.assets[1]!, "ADD_COLLATERAL", 100_000_000n)).toBe(1160000000000000000n); });
  it("rejects repayment above the specific reserve debt", () => { const p = normalize(); expect(() => portfolioOutcome(p, p.assets[3]!, "REPAY_DEBT", 401_000_000n)).toThrow(); });
  it("feeds real-shaped normalized inputs into MEI", () => { const result = evaluateProtection(normalize(), previewPolicy, context); expect(result.action).toBe("REPAY_DEBT"); expect(result.selectedCandidate?.tokenAmount).toBe("266.666667"); expect(result.candidates.some(c => c.type === "REPAY_DEBT" && c.tokenAmount === "266.666666" && !c.reachesTarget)).toBe(true); });
  it("preserves sub-micro HF risk boundaries", () => { const p = normalize(); p.healthFactorWad = "1299999999999999999"; expect(evaluateProtection(p, previewPolicy, context).riskLevel).toBe("HIGH"); });
  it("blocks eMode estimates while retaining raw position", () => { const p = normalizeAavePosition(accountFor(reserves), reserves, baseUnit, 1n); expect(evaluateProtection(p, previewPolicy, context).status).toBe("NO_SAFE_ACTION"); expect(p.assets).toHaveLength(4); });
  it("blocks inconsistent reserve debt totals", () => { const p = normalizeAavePosition({ ...accountFor(reserves), totalDebtBase: 1n }, reserves, baseUnit, 0n); expect(p.analysisBlockers).toContain("DEBT_RECONCILIATION_FAILED"); });
  it("supplied-only position is safe", () => { const rows = reserves.filter(r => r.variableDebt === 0n); const p = normalizeAavePosition(accountFor(rows), rows, baseUnit, 0n); expect(evaluateProtection(p, previewPolicy, context).action).toBe("NO_ACTION"); });
  it("approval and daily limits apply to portfolio candidates", () => { expect(evaluateProtection(normalize(), { ...previewPolicy, approvalRequiredAboveUsd: "1" }, context).action).toBe("REQUIRE_APPROVAL"); expect(evaluateProtection(normalize(), previewPolicy, { ...context, dailyAutonomousSpendUsd: "999" }).status).toBe("NO_SAFE_ACTION"); });
  it("blocks supply cap overflow", () => { const p = normalize(); p.assets[0]!.supplyCapacity = "1"; expect(evaluateProtection(p, { ...previewPolicy, allowRepay: false }, context).candidates.some(c => c.rejectionReason === "SUPPLY_CAP")).toBe(true); });
  it("retains no-action zero debt semantics", () => { const p = normalizeAavePosition(accountFor([]), [], baseUnit, 0n); expect(evaluateProtection(p, previewPolicy, context).status).toBe("NO_ACTION"); });
});
